version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 5173:5173
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front
      - back
  front:
    build: ./front
    restart: always
  back:
    build: ./back
    restart: always
    depends_on:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: passForMongo
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: passForMongo