events {}

http {
  server {
    listen 5173;
    error_log /dev/stdout info;
    access_log /dev/stdout;

    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html;
    }

    location /api/ {
      proxy_pass http://back:3000/;
    }
  }
}